---
- name: checks if extension is installed
  stat:
    path: "{{ user_home }}/.vscode/extensions/{{ item }}"
  register: vscode_extension

- name: installs extension for Visual Studio Code
  command: "'/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' --install-extension {{ item }}"
  when: not vscode_extension.stat.exists
