- name: Make sure zsh is installed
  homebrew:
    name: zsh
    state: present
    path: "{{ homebrew_brew_bin_path }}"

- name: Add valid zsh to /etc/shells
  lineinfile:
    line: /bin/zsh
    dest: /etc/shells
    state: present
  become: true
  become_method: sudo
  notify:
    - set_zsh
