user_home: "{{ '~' | expanduser }}"

dotfiles_repo: https://github.com/flandrade/dotfiles.git
dotfiles_destination: "{{ user_home }}/dotfiles"
dotfiles_version: HEAD
dotfiles_vscode: "{{ user_home }}/Library/Application Support/Code/User/settings.json"

homebrew_taps:
  - heroku/brew
  - homebrew/cask-fonts
  - homebrew/core

homebrew_packages:
  - asdf
  - bat
  - catimg
  - coreutils
  - curl
  - diff-so-fancy
  - exa
  - git
  - gpg
  - grep
  - heroku
  - htop
  - imagemagick
  - jpegoptim
  - ncdu
  - nmap
  - nvm
  - optipng
  - postgres
  - redis
  - speedtest_cli
  - stow
  - stripe/stripe-cli/stripe
  - the_silver_searcher
  - tldr
  - tmate
  - tmux
  - trash
  - tree
  - unrar
  - vim
  - watch
  - wget
  - zsh

homebrew_cask_packages:
  - 1password
  - arq
  - brave-browser
  - cyberduck
  - docker
  - evernote
  - firefox
  - font-fira-code
  - gimp
  - google-chrome
  - iterm2
  - kindle
  - maccy
  - mullvadvpn
  - ngrok
  - postgres
  - postman
  - slack
  - spotify
  - the-unarchiver
  - virtualbox
  - visual-studio-code
  - zoomus

vscode_extensions:
  - CoenraadS.bracket-pair-colorizer-2
  - EditorConfig.EditorConfig
  - GrapeCity.gc-excelviewer
  - HookyQR.beautify
  - Zignd.html-css-class-completion
  - dbaeumer.vscode-eslint
  - dracula-theme.theme-dracula
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - mikestead.dotenv
  - mkaufman.HTMLHint
  - oderwat.indent-rainbow
  - pranaygp.vscode-css-peek
  - redhat.vscode-yaml
  - streetsidesoftware.code-spell-checker
  - vscode-icons-team.vscode-icons
  - vscodevim.vim
  - yzhang.markdown-all-in-one
  - wix.vscode-import-cost
